import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // studio/ is its own app with its own eslint config
    "studio/**",
    // Generated by Sanity TypeGen — don't lint it (or edit it).
    "src/sanity.types.ts",
  ]),
]);

export default eslintConfig;
